Repository UMC-I/Server, pull requests merged in 2025-01, with the labels that each got.

#2 [✨ feature] 프리즈마 세팅
  .env
  .idea/.gitignore
  .idea/Server.iml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  prisma/schema.prisma
  src/errors/errors.js
  src/index.js
  src/services/user.service.js
Labels: ✨ feature

#6 카카오톡 구현
  .env
  package-lock.json
  package.json
  prisma/migrations/20250111115748_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/auth.config.js
  src/index.js
Labels: ✨ feature

#9 [📜 docs] swagger작성
  prisma/schema.prisma
  src/controllers/posts.controller.js
  src/controllers/user.controller.js
  src/index.js
Labels: :scroll: docs

#15 나의 꿈 비공개 여부 수정
  prisma/migrations/20250111150147_/migration.sql
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: ✨ feature

#16 나의 꿈 비공개 여부 수정
  src/dtos/user.dto.js
Labels: ✨ feature

#20 에러핸들링
  prisma/schema.prisma
  src/controllers/post.controller.js
  src/controllers/user.controller.js
  src/dtos/post.dto.js
  src/dtos/user.dto.js
  src/errors/post.errors.js
  src/errors/user.errors.js
  src/index.js
  src/repositories/post.repository.js
  src/repositories/user.repository.js
  src/services/post.service.js
  src/services/user.service.js
Labels: ✨ feature

#26 게시물 좋아요 누르기
  prisma/migrations/20250111181453_/migration.sql
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/errors/post.errors.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: ✨ feature

#27 [✨ feature] 꿈 상세 조회
  src/controllers/post.controller.js
  src/controllers/user.controller.js
  src/dtos/post.dto.js
  src/dtos/user.dto.js
  src/errors/post.errors.js
  src/repositories/post.repository.js
  src/services/post.service.js
  src/services/user.service.js
Labels: ✨ feature

#29 [RE] 내 꿈 목록 조회 페이징 기능 추가
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :recycle: refeator
